### ISSUE TITLE
Не все файлы проекта залились в репозиторий

### ISSUE THREAD

**Issue by MyNameIsAlexandro** [DenSamara1978/SwiftQuiz#1]
<img width="266" alt="Screenshot 2020-06-04 at 19 36 15" src="https://user-images.githubusercontent.com/9446761/83785953-b7f9d780-a69a-11ea-81d3-53cb924cae9a.png">

Денис, проверьте пожалуйста репозиторий, не все файлы залились, и как следствие невозможно оценить, как поправите, напишите мне, я посмотрю

**Comment by DenSamara1978** [comment]
Git у меня файл проекта "зажал", а я не проследил...
Должно быть теперь нормально.
